### PR TITLE
Feature/dimensions handler

### PR DESCRIPTION
**Pull request by fhaefker**
As announced by the "Infobrief 01-19: Zeitliche Dimensionen" and at the release note for Mapbender 3.0.8 the dimensions handler is now a part of the Mapbender - however in an early state of development

### CODE REVIEW

**Comment by astroidex** [comment]
@CharlyUnicorn documentation should contain the information how to activate the element. It is hidden in 3.0.8.

See also Pull request : https://github.com/mapbender/mapbender-starter/pull/90

Please mind 4 spaces

```
    # parameters.yml:
    mapbender.preview.element.dimensionshandler: true
```

**Comment by CharlyUnicorn** [comment]
Activation via parameters.yml is no longer needed - I would suggest adding the documentation very quickly, but we should test the functions of this module with different WMS. I tested it with a wms where you can change the year and month of multiple services (time slider as element and not in the sidepane).

**Comment by astroidex** [comment]
> Activation via parameters.yml is no longer needed - I would suggest adding the documentation very quickly, but we should test the functions of this module with different WMS. I tested it with a wms where you can change the year and month of multiple services (time slider as element and not in the sidepane).

Yes. The element was activated by default in version 3.0.8.1.

**Comment by astroidex** [comment]
You find some issues concerning dimensionsHandler at https://github.com/mapbender/mapbender/issues/
* in ticket 1166 you find 2 WMS for testing: https://github.com/mapbender/mapbender/issues/1166

**Comment by CharlyUnicorn** [comment]
@fhaefker the documentation is up to date and in my opinion you can merge this - in the future we could make some nicer screenshots

**Pull request merged**
